version: '3.8'

networks:
  stt-network:
    driver: bridge

services:
  db:
    build:
      context: ./Database
    networks:
      - stt-network
    ports:
      - "5432:5432"
    env_file:
      - .env
    container_name: stt-db

  frontend:
    build:
      context: .
    networks:
      - stt-network
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: stt-frontend

  nginx:
    image: nginx:1.25.2-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.comf:ro
    networks:
      - stt-network
    ports:
      - "80:80"
    depends_on:
      - frontend
    container_name: stt-nginx
