# Generated by Django 4.1.1 on 2022-09-21 06:41

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('sub_title', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('content', django_quill.fields.QuillField()),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('-published_on',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=500)),
                ('sub_heading', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='photos/portfolio')),
                ('attribution', models.CharField(blank=True, max_length=255)),
                ('completed_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_img', models.ImageField(upload_to='photos/team')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=120)),
                ('facebook', models.URLField(blank=True, max_length=255)),
                ('twitter', models.URLField(blank=True, max_length=255)),
                ('linkedin', models.URLField(blank=True, max_length=255)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
