# Generated by Django 4.1.1 on 2022-09-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahihi_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
    ]
