# Generated by Django 4.1.1 on 2022-09-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahihi_main', '0002_alter_portfolio_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamMember',
        ),
    ]
