# Generated by Django 4.1.1 on 2022-09-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahihi_main', '0003_rename_team_teammember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='PortfolioItem',
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'verbose_name': 'Portfolio Item', 'verbose_name_plural': 'Portfolios Items'},
        ),
    ]
