# Generated by Django 4.1.1 on 2022-09-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahihi_main', '0004_rename_portfolio_portfolioitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='title',
            new_name='heading',
        ),
    ]
