# Generated by Django 4.1.1 on 2022-09-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahihi_main', '0005_rename_title_portfolioitem_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='sub_title',
            new_name='sub_heading',
        ),
    ]
