# Generated by Django 4.1.1 on 2022-09-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahihi_main', '0007_portfolioitem_attribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'verbose_name': 'Portfolio Item', 'verbose_name_plural': 'Portfolio Items'},
        ),
    ]
