# Official PostgreSQL
FROM postgres:15.4-alpine3.18

WORKDIR /Database

# Environment varibles

# ENV POSTGRES_DB=sahihidb
# ENV POSTGRES_USER=sahihiadmin
# ENV POSTGRES_PASSWORD=0123456789

# Expose port
EXPOSE 5432

# Start server

CMD ["postgres"]

